#!/bin/bash

echo -e "\
<!---
THIS FILE IS AUTOMATICALLY GENERATED FROM ALL OTHER PAGES AT EACH REBUILD,
SO DONT EDIT IT, YOUR CHANGES WILL BE LOST !
-->\n"

# grep + awk instead of glob to have same order as in sidebar
for file in $(grep -o -P '(?<=\().*(?=\))' navbar.md \
	| awk '{gsub("html","md"); print "content/" $1}')
do
	echo "$(<$file)"
	echo -e "\n---\n"
done

# - [ View as one big page ]( fullbook.html )
