#!/bin/bash

{
echo -e "\
<!---
THIS FILE IS AUTOMATICALLY GENERATED FROM ALL OTHER PAGES AT EACH REBUILD,
SO DONT EDIT IT, YOUR CHANGES WILL BE LOST !
-->\n"

for file in $( grep -o -P '(?<=\().*(?=\))' navbar.md \
	| awk '{gsub("html","md"); print "content/" $1}' )
do
	echo -e "$(<$file)\n"
done

} > content/fullbook.md

# - [ View as one big page ]( fullbook.html )
